### ISSUE TITLE
Got Access Token but auth fails. Configuration issue?

### ISSUE THREAD

**Issue by vladimir-light** [klapaudius/FOSOAuthServerBundle#10]
Any improved docs to get it work or how to configure my firewalls?

I have several firewalls configured, and they worked fine with  old "vanilla" FOSOAuthServerBundle.

```yml
firewalls:
     ...
     oauth_token:
          pattern:    ^/oauth/v2/token
          security:   false
          
     oauth_authorize:
          pattern:    ^/oauth/v2/auth
          custom_authenticator: .... 
          
     api:
          pattern: ^/api/v1/
          fos_oauth:  true 
          stateless:  true        
```

But with this bundle, I do get **working** access-token (regardless of `grant_type` I use) but authentication with this token fails → `UserNotFoundException`

`FOS\OAuthServerBundle\Security\Authenticator\Oauth2Authenticator::authenticate()` get hit and returns a valid `new SelfValidatingPassport()` but then, for some reason, `EntityUserProvider` from `Symfony\Bridge\Doctrine\Security\User` comes into play and, of course, do not find any User in UserRepo by client_public_id ( https://github.com/klapaudius/FOSOAuthServerBundle/blob/3.0/Security/Authenticator/Oauth2Authenticator.php#L90 )

In my case, I could not step in into `FOS\OAuthServerBundle\Security\Authentication\Provider\OAuthProvider` while debugging.

Do I miss something?
